# Generated by Django 5.2.7 on 2025-11-08 10:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('icon_links', 10), ('horizontal_slider', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Quick Access', 'help_text': 'Section title (optional)', 'max_length': 200}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Show the section title', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': "Icon name (e.g., 'home', 'phone', 'mail', 'map')", 'max_length': 50}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Link title', 'max_length': 100}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Check if this links to an external website', 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'help_text': "External URL (only used if 'External Link' is checked)", 'required': False}), 6: ('wagtail.blocks.PageChooserBlock', (), {'help_text': "Internal page to link to (only used if 'External Link' is NOT checked)", 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('icon_name', 2), ('title', 3), ('is_external_link', 4), ('external_url', 5), ('page_link', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'label': 'Icon Links', 'max_num': 8, 'min_num': 1}), 9: ('wagtail.blocks.CharBlock', (), {'default': '4', 'help_text': 'Number of columns (1-4)', 'max_length': 1}), 10: ('wagtail.blocks.StructBlock', [[('title', 0), ('show_title', 1), ('links', 8), ('columns', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'Our Services', 'help_text': 'Section title', 'max_length': 200}), 12: ('wagtail.blocks.TextBlock', (), {'help_text': 'Section description', 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'default': '1', 'help_text': 'Display order (1, 2, 3, etc.)', 'max_length': 3}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Slide title', 'max_length': 200}), 15: ('wagtail.blocks.TextBlock', (), {'help_text': 'Slide description', 'required': False}), 16: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Slide image'}), 17: ('wagtail.blocks.CharBlock', (), {'default': 'Learn More', 'help_text': 'Text for the slide button', 'max_length': 50}), 18: ('wagtail.blocks.StructBlock', [[('order', 13), ('title', 14), ('description', 15), ('image', 16), ('button_text', 17), ('is_external_link', 4), ('external_url', 5), ('page_link', 6)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {'label': 'Slides', 'max_num': 10, 'min_num': 1}), 20: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Enable slider autoplay'}), 21: ('wagtail.blocks.CharBlock', (), {'default': '3000', 'help_text': 'Autoplay delay in milliseconds', 'max_length': 10}), 22: ('wagtail.blocks.StructBlock', [[('title', 11), ('description', 12), ('slides', 19), ('autoplay_enabled', 20), ('autoplay_delay', 21)]], {})}, default=list, help_text='Main page content using flexible blocks'),
        ),
    ]
